Changelog: - Replace the brunch toolchain by a ChromiumOS Stage3.

diff --git a/scripts/build-init b/scripts/build-init
--- a/scripts/build-init
+++ b/scripts/build-init
@@ -1,34 +1,28 @@
 #!/bin/bash
-export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 export HOME=/home/chronos
-export LD_LIBRARY_PATH=/home/chronos/ncurses-pkg/usr/lib64:/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/lib64:/lib
-export C_INCLUDE_PATH=/home/chronos/ncurses-pkg/usr/include:/usr/local/include:/usr/include
-export PKG_CONFIG_PATH=/home/chronos/ncurses-pkg/usr/lib64/pkgconfig:/home/chronos/efibootmgr-pkg/usr/lib64/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig
 export LC_ALL=C
+export LD_LIBRARY_PATH=/home/chronos/ncurses-pkg/usr/lib64:/home/chronos/swtpm-pkg/usr/libswtpm:/home/chronos/efibootmgr-pkg/usr/lib64:/usr/lib64:/lib64
+export C_INCLUDE_PATH=/home/chronos/ncurses-pkg/usr/include:/home/chronos/swtpm-pkg/usr/include:/home/chronos/efibootmgr-pkg/usr/include:/usr/include
+export PKG_CONFIG_PATH=/home/chronos/ncurses-pkg/usr/lib64/pkgconfig:/home/chronos/swtpm-pkg/usr/lib64/pkgconfig:/home/chronos/efibootmgr-pkg/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig
 
 cd /home/chronos/
 
-version="$(/opt/google/chrome/chrome --version)"
+version="$(LD_LIBRARY_PATH=/chromeos/usr/lib64:/chromeos/lib64 /chromeos/opt/google/chrome/chrome --version)"
 version=r"${version:14:3}"
-[ ! "$version" == "" ] || { echo "Failed to identify ChromeOS version"; exit 1; }
+[ ! "$version" == "r" ] || { echo "Failed to identify ChromeOS version"; exit 1; }
 echo "Entered chroot with recovery version $version"
 
+sudo mkdir -p /usr/local
 sudo chown 1000:1000 /usr/local || { echo "Failed to change ownership of /usr/local"; exit 1; }
 
-if [ ! -f brunch_toolchain.tar.gz ]; then
-	curl -L -s $(curl -L -s "https://api.github.com/repos/sebanc/brunch-toolchain/releases/latest" | grep browser_download_url | tr -d '"' | sed 's#browser_download_url: ##g') -o brunch_toolchain.tar.gz || { echo "Failed to download the brunch toolchain"; exit 1; }
-fi
-tar zxf brunch_toolchain.tar.gz -C /usr/local || { echo "Failed to extract the brunch toolchain"; exit 1; }
-
-# Temporary fix
-if [ ! -f /lib64/libnsl.so.2 ]; then sudo ln -sf libnsl.so.1 /lib64/libnsl.so.2; fi
-
-mkdir -p ./version-pkg/etc || { echo "Failed to make the brunch version package"; exit 1; }
-echo "Brunch $version $(date +"%Y%m%d")" > ./version-pkg/etc/brunch_version || { echo "Failed to make the brunch version package"; exit 1; }
-cd ./version-pkg || { echo "Failed to make the brunch version package"; exit 1; }
-tar zcvf ../rootc/packages/version.tar.gz * --owner=0 --group=0 || { echo "Failed to make the brunch version package"; exit 1; }
-cd .. || { echo "Failed to make the brunch version package"; exit 1; }
-rm -rf ./version-pkg || { echo "Failed to make the brunch version package"; exit 1; }
+mkdir -p ./base-pkg/etc ./base-pkg/usr/lib64 ./base-pkg/usr/sbin || { echo "Failed to make the brunch base package"; exit 1; }
+cd ./base-pkg || { echo "Failed to make the brunch base package"; exit 1; }
+echo "Brunch $version $(date +"%Y%m%d")" > ./etc/brunch_version || { echo "Failed to make the brunch base package"; exit 1; }
+cp "$(echo $(dirname $(gcc -print-libgcc-file-name))/libstdc++.so.6)" ./usr/lib64/ || { echo "Failed to make the brunch base package"; exit 1; }
+for i in $(LD_LIBRARY_PATH=/usr/lib64:/lib64:/chromeos/usr/lib64:/chromeos/lib64 ldd /chromeos/usr/sbin/efibootmgr | grep '/chromeos' | cut -d' ' -f3); do cp "$i" ./usr/lib64/ || { echo "Failed to make the brunch base package"; exit 1; }; done
+cp /chromeos/usr/sbin/efibootmgr ./usr/sbin/ || { echo "Failed to make the brunch base package"; exit 1; }
+tar zcvf ../rootc/packages/base.tar.gz * --owner=0 --group=0 || { echo "Failed to make the brunch base package"; exit 1; }
+cd .. || { echo "Failed to make the brunch base package"; exit 1; }
 
 mkdir -p ./initramfs/{bin,lib64,sbin} || { echo "Failed to make initramfs directories"; exit 1; }
 mkdir -p ./binaries-pkg/usr/bin ./binaries-pkg/usr/sbin || { echo "Failed to make binaries package directories"; exit 1; }
@@ -91,11 +85,10 @@ cd .. || { echo "Failed to make minioverride"; exit 1; }
 rm -rf ./minioverride || { echo "Failed to make minioverride"; exit 1; }
 
 cd ./binaries-pkg || { echo "Failed to make binaries package archive"; exit 1; }
-cp /usr/local/bin/ldd ./usr/bin/ || { echo "Failed to make binaries package archive"; exit 1; }
-cp /usr/local/bin/strings ./usr/bin/ || { echo "Failed to make binaries package archive"; exit 1; }
+cp /usr/bin/ldd ./usr/bin/ || { echo "Failed to make binaries package archive"; exit 1; }
+cp /usr/bin/strings ./usr/bin/ || { echo "Failed to make binaries package archive"; exit 1; }
 tar zcvf ../rootc/packages/binaries.tar.gz * --owner=0 --group=0 || { echo "Failed to make binaries package archive"; exit 1; }
 cd .. || { echo "Failed to make binaries package archive"; exit 1; }
-rm -rf ./binaries-pkg || { echo "Failed to make binaries package archive"; exit 1; }
 
 git clone --depth=1 -b master https://github.com/godspeed1989/fbv.git fbv || { echo "Failed to make fbv"; exit 1; }
 cd ./fbv || { echo "Failed to make fbv"; exit 1; }
@@ -115,20 +108,19 @@ make install || { echo "Failed to make libfmt"; exit 1; }
 cd ../.. || { echo "Failed to make libfmt"; exit 1; }
 rm -rf ./fmt || { echo "Failed to make libfmt"; exit 1; }
 
-git clone -b v2 https://github.com/linux-surface/iptsd.git iptsd || { echo "Failed to make iptsd"; exit 1; }
+git clone -b v3.0.1 https://github.com/linux-surface/iptsd.git iptsd || { echo "Failed to make iptsd"; exit 1; }
 cd iptsd || { echo "Failed to make iptsd"; exit 1; }
 sed -i "s@'-Wconversion',@'-Wconversion', '-Wno-pedantic',@g" ./src/meson.build
-meson --prefix="/usr" -Dservice_manager="" -Ddebug_tools="" build/ || { echo "Failed to make iptsd"; exit 1; }
+meson setup --prefix="/usr" -Dservice_manager="" -Ddebug_tools="" build/ || { echo "Failed to make iptsd"; exit 1; }
 DESTDIR=/home/chronos/ipts-pkg ninja -j"$NTHREADS" -C build/ install || { echo "Failed to make iptsd"; exit 1; }
+cp -r /usr/local/* ../ipts-pkg/usr/
+mkdir -p ../ipts-pkg/usr/lib64 || { echo "Failed to make iptsd"; exit 1; }
 cd .. || { echo "Failed to make iptsd"; exit 1; }
 rm -rf ./iptsd || { echo "Failed to make iptsd"; exit 1; }
 cd ./ipts-pkg || { echo "Failed to make iptsd"; exit 1; }
-mkdir -p ./usr/lib64 || { echo "Failed to make iptsd"; exit 1; }
-for i in $(ldd ./usr/bin/iptsd | grep "/usr/local/lib" | grep -v ld-linux | cut -d' ' -f3); do if [ ! -f $(echo "$i" | sed "s#/local##g") ] && [ ! -f $(echo "$i" | sed "s#/usr/local##g") ]; then cp "$i" ./usr/lib64/ || { echo "Failed to make iptsd"; exit 1; }; fi; done
 rm -rf ./usr/include ./usr/lib64/pkgconfig ./usr/share/pkgconfig || { echo "Failed to make iptsd"; exit 1; }
 tar zcvf ../rootc/packages/ipts.tar.gz * --owner=0 --group=0 || { echo "Failed to make iptsd"; exit 1; }
 cd .. || { echo "Failed to make iptsd"; exit 1; }
-rm -rf ./fmt-pkg ./ipts-pkg || { echo "Failed to make iptsd"; exit 1; }
 
 git clone --depth=1 -b v1.9.18 https://github.com/jirka-h/haveged.git || { echo "Failed to make haveged"; exit 1; }
 cd haveged || { echo "Failed to make haveged"; exit 1; }
@@ -141,65 +133,30 @@ cp ../haveged-pkg/usr/lib64/libhavege.so* ../initramfs/lib64/ || { echo "Failed 
 cd .. || { echo "Failed to make haveged"; exit 1; }
 rm -rf ./haveged || { echo "Failed to make haveged"; exit 1; }
 
-git clone --depth=1 -b popt-1.18-release https://github.com/rpm-software-management/popt.git || { echo "Failed to make popt"; exit 1; }
-cd ./popt || { echo "Failed to make popt"; exit 1; }
-./autogen.sh || { echo "Failed to make popt"; exit 1; }
-./configure --prefix=/usr --libdir=/usr/lib64 || { echo "Failed to make popt"; exit 1; }
-make -j"$NTHREADS" || { echo "Failed to make popt"; exit 1; }
-make DESTDIR=/home/chronos/efibootmgr-pkg install || { echo "Failed to make popt"; exit 1; }
-cd .. || { echo "Failed to make popt"; exit 1; }
-rm -rf ./popt || { echo "Failed to make popt"; exit 1; }
-
-git clone --depth=1 -b 37 https://github.com/rhboot/efivar.git || { echo "Failed to make efivar"; exit 1; }
-cd ./efivar || { echo "Failed to make efivar"; exit 1; }
-sed -i "s# --add-needed##g" ./gcc.specs || { echo "Failed to make efivar"; exit 1; }
-make -j"$NTHREADS" CFLAGS="-Wno-address-of-packed-member" || { echo "Failed to make efivar"; exit 1; }
-make DESTDIR=/home/chronos/efibootmgr-pkg install || { echo "Failed to make efivar"; exit 1; }
-sed -i "s#/usr#/home/chronos/efibootmgr-pkg/usr#g" /home/chronos/efibootmgr-pkg/usr/lib64/pkgconfig/* || { echo "Failed to make efivar"; exit 1; }
-cd .. || { echo "Failed to make efivar"; exit 1; }
-rm -rf ./efivar || { echo "Failed to make efivar"; exit 1; }
-
-git clone --depth=1 -b 17 https://github.com/rhboot/efibootmgr.git || { echo "Failed to make efibootmgr"; exit 1; }
-cd ./efibootmgr || { echo "Failed to make efibootmgr"; exit 1; }
-sed -i "s#extern int efi_set_verbose#extern void efi_set_verbose#g" ./src/efibootmgr.c || { echo "Failed to make efibootmgr"; exit 1; }
-make -j"$NTHREADS" EFIDIR=boot EFI_LOADER=grubx64.efi CFLAGS="-Wno-pointer-sign" C_INCLUDE_PATH=/home/chronos/efibootmgr-pkg/usr/include || { echo "Failed to make efibootmgr"; exit 1; }
-make EFIDIR=boot EFI_LOADER=grubx64.efi DESTDIR=/home/chronos/efibootmgr-pkg install || { echo "Failed to make efibootmgr"; exit 1; }
-cd .. || { echo "Failed to make efibootmgr"; exit 1; }
-rm -rf ./efibootmgr || { echo "Failed to make efibootmgr"; exit 1; }
-
-cd ./efibootmgr-pkg || { echo "Failed to make efibootmgr package"; exit 1; }
-rm -rf ./usr/include ./usr/lib64/pkgconfig ./usr/share/pkgconfig || { echo "Failed to make efibootmgr package"; exit 1; }
-tar zcvf ../rootc/packages/efibootmgr.tar.gz * --owner=0 --group=0 || { echo "Failed to make efibootmgr package"; exit 1; }
-cd .. || { echo "Failed to make efibootmgr package"; exit 1; }
-rm -rf ./efibootmgr-pkg || { echo "Failed to make efibootmgr package"; exit 1; }
-
-git clone https://github.com/stefanberger/libtpms.git libtpms || { echo "Failed to make libtpms"; exit 1; }
+git clone -b v0.9.7 https://github.com/stefanberger/libtpms.git libtpms || { echo "Failed to make libtpms"; exit 1; }
 cd ./libtpms || { echo "Failed to make libtpms"; exit 1; }
-git checkout df1c3e98d697f3c1f09262d2ba161a7db784d6cc || { echo "Failed to make libtpms"; exit 1; }
-./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib64 --with-openssl --with-tpm2 --enable-debug || { echo "Failed to make libtpms"; exit 1; }
+./autogen.sh --prefix=/usr --libdir=/usr/lib64 --with-openssl --with-tpm2 --disable-tests || { echo "Failed to make libtpms"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make libtpms"; exit 1; }
-make install || { echo "Failed to make libtpms"; exit 1; }
+make DESTDIR=/home/chronos/swtpm-pkg install || { echo "Failed to make libtpms"; exit 1; }
+sed -i "s#/usr#/home/chronos/swtpm-pkg/usr#g" /home/chronos/swtpm-pkg/usr/lib64/pkgconfig/* || { echo "Failed to make libtpms"; exit 1; }
 cd .. || { echo "Failed to make libtpms"; exit 1; }
 rm -rf ./libtpms || { echo "Failed to make libtpms"; exit 1; }
 
-git clone https://github.com/stefanberger/swtpm.git swtpm || { echo "Failed to make swtpm"; exit 1; }
+git clone -b v0.9.0 https://github.com/stefanberger/swtpm.git swtpm || { echo "Failed to make swtpm"; exit 1; }
 cd ./swtpm || { echo "Failed to make swtpm"; exit 1; }
-git checkout f2268eebb0d1adf89bad83fa4cf91e37b4e3fa53 || { echo "Failed to make swtpm"; exit 1; }
-sed -i '/AC_CONFIG_SRCDIR/ a AC_CONFIG_AUX_DIR([.])' ./configure.ac || { echo "Failed to make swtpm"; exit 1; }
-./autogen.sh --prefix=/usr --libdir=/usr/lib64 --enable-debug --disable-python-installation with_seccomp=no with_gnutls=no with_cuse=no || { echo "Failed to make swtpm"; exit 1; }
+./autogen.sh --prefix=/usr --libdir=/usr/lib64 --disable-python-installation --disable-tests with_seccomp=no with_gnutls=no with_cuse=no || { echo "Failed to make swtpm"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make swtpm"; exit 1; }
 make DESTDIR=/home/chronos/swtpm-pkg install || { echo "Failed to make swtpm"; exit 1; }
-for i in $(ldd ../swtpm-pkg/usr/bin/swtpm | grep "/usr/local/lib" | grep -v ld-linux | cut -d' ' -f3); do if [ ! -f $(echo "$i" | sed "s#/local##g") ] && [ ! -f $(echo "$i" | sed "s#/usr/local##g") ]; then cp "$i" ../swtpm-pkg/usr/lib64/ || { echo "Failed to make swtpm"; exit 1; }; fi; done
+rm $(find ../swtpm-pkg/usr/lib64/swtpm -type f | grep -v '.so') || { echo "Failed to make swtpm package"; exit 1; }
+mv ../swtpm-pkg/usr/lib64/*.so* ../swtpm-pkg/usr/lib64/swtpm/ || { echo "Failed to make swtpm package"; exit 1; }
+mv ../swtpm-pkg/usr/lib64/swtpm ../swtpm-pkg/usr/libswtpm || { echo "Failed to make swtpm package"; exit 1; }
+for i in $(ldd ../swtpm-pkg/usr/bin/swtpm | grep -v 'ld-linux' | grep -v '/swtpm-pkg/' | cut -d' ' -f3); do echo "*** importing $i to /usr/libswtpm ***"; cp "$i" ../swtpm-pkg/usr/libswtpm/ || { echo "Failed to make swtpm package"; exit 1; }; done
 cd .. || { echo "Failed to make swtpm"; exit 1; }
 rm -rf ./swtpm || { echo "Failed to make swtpm"; exit 1; }
-cd ./swtpm-pkg/usr/lib64 || { echo "Failed to make swtpm package"; exit 1; }
-mv ./swtpm/* ./ || { echo "Failed to make swtpm package"; exit 1; }
-rm -r `ls | grep -v '.so'` || { echo "Failed to make swtpm package"; exit 1; }
-cd ../.. || { echo "Failed to make swtpm package"; exit 1; }
-rm -rf ./etc ./var ./usr/include ./usr/lib64/pkgconfig ./usr/share/pkgconfig || { echo "Failed to make swtpm package"; exit 1; }
+cd ./swtpm-pkg || { echo "Failed to make swtpm package"; exit 1; }
+rm -rf ./etc ./var ./usr/include ./usr/lib64 || { echo "Failed to make swtpm package"; exit 1; }
 tar zcvf ../rootc/packages/swtpm.tar.gz * --owner=0 --group=0 || { echo "Failed to make swtpm package"; exit 1; }
 cd .. || { echo "Failed to make swtpm package"; exit 1; }
-rm -rf ./swtpm-pkg || { echo "Failed to make swtpm package"; exit 1; }
 
 git clone --depth=1 -b master https://github.com/mirror/ncurses.git || { echo "Failed to make ncurses"; exit 1; }
 cd ./ncurses || { echo "Failed to make ncurses"; exit 1; }
@@ -213,17 +170,16 @@ rm -rf ./ncurses || { echo "Failed to make ncurses"; exit 1; }
 git clone --depth=1 -b master https://git.savannah.gnu.org/git/nano.git || { echo "Failed to make nano"; exit 1; }
 cd ./nano || { echo "Failed to make nano"; exit 1; }
 ./autogen.sh || { echo "Failed to make nano"; exit 1; }
-./configure --prefix=/usr --libdir=/usr/lib64 CFLAGS="-lncurses" || { echo "Failed to make nano"; exit 1; }
+./configure --prefix=/usr --libdir=/usr/lib64 --disable-libmagic || { echo "Failed to make nano"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make nano"; exit 1; }
 make DESTDIR=/home/chronos/nano-pkg install || { echo "Failed to make nano"; exit 1; }
 mkdir -p ../nano-pkg/usr/lib64 || { echo "Failed to make nano"; exit 1; }
-for i in $(ldd ../nano-pkg/usr/bin/nano | grep "/usr/local/lib" | grep -v ld-linux | cut -d' ' -f3); do if [ ! -f $(echo "$i" | sed "s#/local##g") ] && [ ! -f $(echo "$i" | sed "s#/usr/local##g") ]; then cp "$i" ../nano-pkg/usr/lib64/ || { echo "Failed to make nano"; exit 1; }; fi; done
 cd ../nano-pkg || { echo "Failed to make nano"; exit 1; }
 cp -r ../ncurses-pkg/usr/share/terminfo ./usr/share/ || { echo "Failed to make nano"; exit 1; }
 rm -rf ./usr/include ./usr/lib64/pkgconfig ./usr/share/pkgconfig || { echo "Failed to make nano"; exit 1; }
 tar zcvf ../rootc/packages/nano.tar.gz * --owner=0 --group=0 || { echo "Failed to make nano"; exit 1; }
 cd .. || { echo "Failed to make nano"; exit 1; }
-rm -rf ./ncurses-pkg ./nano ./nano-pkg || { echo "Failed to make nano"; exit 1; }
+rm -rf ./ncurses-pkg ./nano || { echo "Failed to make nano"; exit 1; }
 
 git clone --depth=1 -b 4.6.1 https://github.com/plougher/squashfs-tools.git || { echo "Failed to make squashfs-tools"; exit 1; }
 cd squashfs-tools/squashfs-tools || { echo "Failed to make squashfs-tools"; exit 1; }
@@ -261,17 +217,19 @@ for i in $(ldd /sbin/losetup | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Fa
 cp /sbin/losetup ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
 for i in $(ldd /sbin/mkfs.ext4 | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
 cp /sbin/mkfs.ext4 ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
-for i in $(ldd /sbin/modprobe | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
-cp /sbin/modprobe ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
+for i in $(ldd /usr/bin/modprobe | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
+cp /usr/bin/modprobe ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
 for i in $(ldd /usr/bin/ntfs-3g | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
 cp /usr/bin/ntfs-3g ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
 for i in $(ldd /usr/bin/ntfsfix | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
 cp /usr/bin/ntfsfix ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
+for i in $(ldd /usr/bin/pkill | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
+cp /usr/bin/pkill ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
 for i in $(ldd /sbin/resize2fs | cut -d' ' -f3); do cp "$i" ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }; done
 cp /sbin/resize2fs ./sbin/ || { echo "Failed to finalise initramfs"; exit 1; }
 cp /lib64/ld-linux-x86-64.so.2 ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }
-cp /usr/lib64/libgcc_s.so.1 ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }
-sudo chmod 0755 ./sbin/* || { echo "Failed to finalise initramfs"; exit 1; }
+cp $(echo $(dirname $(gcc -print-libgcc-file-name))/libgcc_s.so.1) ./lib64/ || { echo "Failed to finalise initramfs"; exit 1; }
+chmod 0755 ./sbin/* || { echo "Failed to finalise initramfs"; exit 1; }
 find . | cpio -o -H newc | gzip > ../rootc/initramfs.img || { echo "Failed to finalise initramfs"; exit 1; }
 cd .. || { echo "Failed to finalise initramfs"; exit 1; }
 rm -rf ./busybox || { echo "Failed to finalise initramfs"; exit 1; }
