Changelog: - Major update required for ChromeOS r103 - Attempt to add ithc touchscreen support
Warning: due to a change in cryptohome all your data will be lost if you update to this build. Make sure you backup your data and perform a clean brunch install.

diff --git a/scripts/build-init b/scripts/build-init
--- a/scripts/build-init
+++ b/scripts/build-init
@@ -100,12 +100,28 @@ DESTDIR=/home/chronos/ipts-pkg ninja -j"$NTHREADS" -C build/ install || { echo "
 cd .. || { echo "Failed to make iptsd"; exit 1; }
 rm -rf ./iptsd || { echo "Failed to make iptsd"; exit 1; }
 cd ./ipts-pkg || { echo "Failed to make iptsd"; exit 1; }
+mkdir -p ./usr/lib64 || { echo "Failed to make iptsd"; exit 1; }
+cp /usr/local/lib64/libstdc++.so.6 ./usr/lib64/ || { echo "Failed to make iptsd"; exit 1; }
 tar zcvf ../rootc/packages/ipts.tar.gz * --owner=0 --group=0 || { echo "Failed to make iptsd"; exit 1; }
 cd .. || { echo "Failed to make iptsd"; exit 1; }
 rm -rf ./ipts-pkg || { echo "Failed to make iptsd"; exit 1; }
 
+git clone --depth=1 -b libqzed https://github.com/quo/iptsd.git ithcd || { echo "Failed to make ithcd"; exit 1; }
+cd ithcd || { echo "Failed to make ithcd"; exit 1; }
+meson --prefix="/usr" -Dservice_manager="" -Dsample_config=false build/ || { echo "Failed to make ithcd"; exit 1; }
+DESTDIR=/home/chronos/ithc-pkg ninja -j"$NTHREADS" -C build/ install || { echo "Failed to make ithcd"; exit 1; }
+cd .. || { echo "Failed to make ithcd"; exit 1; }
+rm -rf ./ithcd || { echo "Failed to make ithcd"; exit 1; }
+cd ./ithc-pkg || { echo "Failed to make ithcd"; exit 1; }
+mkdir -p ./usr/lib64 || { echo "Failed to make ithcd"; exit 1; }
+cp /usr/local/lib64/libstdc++.so.6 ./usr/lib64/ || { echo "Failed to make ithcd"; exit 1; }
+tar zcvf ../rootc/packages/ithc.tar.gz * --owner=0 --group=0 || { echo "Failed to make ithcd"; exit 1; }
+cd .. || { echo "Failed to make ithcd"; exit 1; }
+rm -rf ./ithc-pkg || { echo "Failed to make ithcd"; exit 1; }
+
 git clone --depth=1 -b master https://github.com/jirka-h/haveged.git || { echo "Failed to make haveged"; exit 1; }
 cd haveged || { echo "Failed to make haveged"; exit 1; }
+autoreconf -i || { echo "Failed to make haveged"; exit 1; }
 ./configure --prefix=/usr --libdir=/usr/lib64 --disable-init --enable-tune=no || { echo "Failed to make haveged"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make haveged"; exit 1; }
 make DESTDIR=/home/chronos/haveged-pkg install || { echo "Failed to make haveged"; exit 1; }
@@ -150,7 +166,7 @@ rm -rf ./efibootmgr-pkg || { echo "Failed to make efibootmgr package"; exit 1; }
 
 git clone --depth=1 -b master https://github.com/stefanberger/libtpms.git || { echo "Failed to make libtpms"; exit 1; }
 cd ./libtpms || { echo "Failed to make libtpms"; exit 1; }
-./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib64 --with-openssl --with-tpm2 || { echo "Failed to make libtpms"; exit 1; }
+./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib64 --with-openssl --with-tpm2 --enable-debug || { echo "Failed to make libtpms"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make libtpms"; exit 1; }
 make install || { echo "Failed to make libtpms"; exit 1; }
 cd .. || { echo "Failed to make libtpms"; exit 1; }
@@ -159,41 +175,29 @@ rm -rf ./libtpms || { echo "Failed to make libtpms"; exit 1; }
 git clone --depth=1 -b master https://github.com/stefanberger/swtpm.git || { echo "Failed to make swtpm"; exit 1; }
 cd ./swtpm || { echo "Failed to make swtpm"; exit 1; }
 sed -i '/AC_CONFIG_SRCDIR/ a AC_CONFIG_AUX_DIR([.])' ./configure.ac || { echo "Failed to make swtpm"; exit 1; }
-./autogen.sh --prefix=/usr --libdir=/usr/lib64 --disable-python-installation with_swtpm_setup=no with_seccomp=no with_gnutls=no with_cuse=no || { echo "Failed to make swtpm"; exit 1; }
+./autogen.sh --prefix=/usr --libdir=/usr/lib64 --enable-debug --disable-python-installation with_seccomp=no with_gnutls=no with_cuse=no || { echo "Failed to make swtpm"; exit 1; }
 make -j"$NTHREADS" || { echo "Failed to make swtpm"; exit 1; }
 make DESTDIR=/home/chronos/swtpm-pkg install || { echo "Failed to make swtpm"; exit 1; }
 for i in $(ldd ../swtpm-pkg/usr/bin/swtpm | grep "/usr/local/lib" | grep -v ld-linux | cut -d' ' -f3); do if [ ! -f $(echo "$i" | sed "s#/local##g") ] && [ ! -f $(echo "$i" | sed "s#/usr/local##g") ]; then cp "$i" ../swtpm-pkg/usr/lib64/ || { echo "Failed to make swtpm"; exit 1; }; fi; done
 cd .. || { echo "Failed to make swtpm"; exit 1; }
 rm -rf ./swtpm || { echo "Failed to make swtpm"; exit 1; }
-
 cd ./swtpm-pkg/usr/lib64 || { echo "Failed to make swtpm package"; exit 1; }
 mv ./swtpm/* ./ || { echo "Failed to make swtpm package"; exit 1; }
 rm -r `ls | grep -v '.so'` || { echo "Failed to make swtpm package"; exit 1; }
-cd ../bin || { echo "Failed to make swtpm package"; exit 1; }
-rm -r `ls swtpm_* | grep -v 'swtpm_ioctl'` || { echo "Failed to make swtpm package"; exit 1; }
 cd ../.. || { echo "Failed to make swtpm package"; exit 1; }
+rm -r ./etc ./var || { echo "Failed to make swtpm package"; exit 1; }
 mkdir -p ./etc/init || { echo "Failed to make swtpm package"; exit 1; }
+cat >./etc/init/tpm2-simulator.conf <<'SWTPM'
+stop on stopping boot-services
 
-#mkdir -p ./swtpm-pkg/etc/init ./swtpm-pkg/usr/bin ./swtpm-pkg/usr/lib64
-#cd ./swtpm-pkg
-#cp /usr/local/bin/swtpm /usr/local/bin/swtpm_ioctl ./usr/bin/
-#for i in $(ldd /usr/local/bin/swtpm | grep "/usr/local/lib" | grep -v ld-linux | cut -d' ' -f3); do if [ ! -f $(echo "$i" | sed "s#/local##g") ] && [ ! -f $(echo "$i" | sed "s#/usr/local##g") ]; then cp "$i" ./usr/lib64/; fi; done
-
-cat >./etc/init/swtpm.conf <<'SWTPM'
-start on stopped startup
-
-script
+pre-start script
    modprobe tpm_vtpm_proxy
-   mkdir -p /var/lib/swtpm
-   if [ -f "/etc/init/trunksd.conf" ]; then
-   	swtpm chardev --vtpm-proxy --tpm2 --tpmstate dir=/var/lib/swtpm --ctrl type=tcp,port=10001 --flags startup-clear
-   else
-   	swtpm chardev --vtpm-proxy --tpmstate dir=/var/lib/swtpm --ctrl type=tcp,port=10001 --flags startup-clear
-   fi
-   swtpm_ioctl --tcp :10001 -i
+   mkdir -p /mnt/stateful_partition/swtpm
 end script
+
+exec swtpm chardev --vtpm-proxy --tpm2 --tpmstate dir=/mnt/stateful_partition/swtpm --ctrl type=unixio,path=/mnt/stateful_partition/swtpm/swtpm.sock --flags not-need-init
 SWTPM
-[ -f ./etc/init/swtpm.conf ] || { echo "Failed to make swtpm package"; exit 1; }
+[ -f ./etc/init/tpm2-simulator.conf ] || { echo "Failed to make swtpm package"; exit 1; }
 tar zcvf ../rootc/packages/swtpm.tar.gz * --owner=0 --group=0 || { echo "Failed to make swtpm package"; exit 1; }
 cd .. || { echo "Failed to make swtpm package"; exit 1; }
 rm -rf ./swtpm-pkg || { echo "Failed to make swtpm package"; exit 1; }
